import type { Metadata } from "next";
import BottomNavigation from "@/components/BottomNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {" "}
      {children} <BottomNavigation />
    </div>
  );
}
